version: '3'
services:
  wordpress:
    container_name: 'wordpress'
    image: wordpress:latest
    ports:
      - 8000:80
    networks:
          - my_network
networks:
  my_network:
    external: true