version: '3'
services:

  mariadb:
   image: mariadb:latest
   container_name: 'mariadb'
   environment:
     MYSQL_USER: 'root'
     MYSQL_ROOT_PASSWORD: 'root'
     MYSQL_DATABASE: 'wordpress'
   ports:
     - 3306:3306
   networks:
     - my_network

networks:
  my_network:
    external: true